# nome do worflow
name: Run E2E Tests

# quanndo executar este workflow
on: [pull_request]

# executar trabalhos
jobs:
  # nome do job
  run-e2e-tests:
    name: Run E2E Tests
    # qual maquina executar testes
    runs-on: ubuntu-latest

    # para rodar testes e2e precisa do banco de dados
    # criar serviço do banco de dados: pegar informações do docker-compose
    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: apisolid

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - run: npm ci

      #   rodar testes e2e
      - run: npm run test:e2e
        env:
          # seta variáveis de ambiente
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"
